def get_pantallas_menu():
    return [
        "Asignaciones",
        "Checklist",
        "Blob Storage",
        "Dashboard Power BI",
        "SNE Asignación",
        "SNE Monitor",
        "SNE Objeción",
        "Control Clausulas",
        "Gestión Kilómetros",
        "Registro EDS",
        "Gestión SGI",
        "Buses CEXP",
        "Centros de Operación",
        "Estación de Servicio",
        "Crear Usuario",
        "Gestión de Roles",
        "Roles Blob Storage",
        "Roles PowerBI",
        "Motivos SNE",
        "Notas Objeción SNE",
        "NPL Chatbot",
        "Rutas CEXP"
    ]