name: 🚀(DEV) Build | Deploy Gestión Express en Azure Web App

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    name: 🏗️ (DEV) Construcción del paquete
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar versión de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: 📥 Instalar dependencias (validación)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 📦 Comprimir archivos para despliegue
        run: |
          zip -r release.zip *.py requirements.txt controller model view static lib \
            -x "**/__pycache__/*" "**/*.pyc" "**/.DS_Store" "*.venv/*" "*.env" ".git/*" ".github/*"

      - name: ☁️ Subir artefacto para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    name: 🚀 (DEV) Despliegue en Azure Web App
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 📥 Descargar artefacto del trabajo de construcción
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 📂 Descomprimir paquete
        run: unzip release.zip

      - name: 🧹 Eliminar release.zip para evitar error ZIP Deploy
        run: rm release.zip

      - name: 📁 Ver contenido descomprimido (debug)
        run: ls -R

      # - name: 🧹 Limpiar wwwroot (opcional, solo si ya desplegaste antes)
      #   run: az webapp ssh --name gestionconsorcioexpress2 --resource-group db_gestionexpress --command "rm -rf /home/site/wwwroot/*"

      - name: 🔐 Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15A57A74A6AF4FCDBAC6C55D19CD4DDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1AE82DC672A4EB7BB8059EC8C400D8E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E8DECC7B07E4CD7B20A6F8A68B5226A }}

      - name: 👤 Ver cuenta autenticada (diagnóstico)
        run: az account show

      - name: 🚀 Desplegar en Azure Web App (ZIP Deploy)
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gestionconsorcioexpress2"
          slot-name: "Production"
          package: .
