name: 🚀(DEV) Build | Deploy Gestión Express en Azure Web App

on:
  push:
    branches: [dev]
  workflow_dispatch:

jobs:
  build:
    name: 🏗️ (DEV) Construcción del paquete
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar versión de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: 📥 Instalar dependencias (validación)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Verificar presencia de archivos clave
        run: |
          if [ ! -f main.py ]; then echo "❌ main.py no encontrado"; exit 1; fi
          if [ ! -f requirements.txt ]; then echo "❌ requirements.txt no encontrado"; exit 1; fi

      - name: 📂 Mostrar estructura del proyecto
        run: |
          echo "📁 Estructura actual:"
          tree -L 2 || ls -R

      - name: 📦 Preparar paquete comprimido (Run From Package)
        run: |
          mkdir deployment
          cp -r *.py requirements.txt controller model view static lib deployment/ 2>/dev/null || true
          cd deployment
          zip -r ../release.zip .
          cd ..

      - name: 🔍 Verificar contenido del ZIP
        run: unzip -l release.zip | grep -E "main\.py|requirements\.txt"

      - name: ☁️ Subir artefacto comprimido
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    name: 🚀 (DEV) Despliegue en Azure Web App
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 📥 Descargar artefacto del trabajo de construcción
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 🔐 Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_15A57A74A6AF4FCDBAC6C55D19CD4DDC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C1AE82DC672A4EB7BB8059EC8C400D8E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5E8DECC7B07E4CD7B20A6F8A68B5226A }}

      - name: 👤 Ver cuenta autenticada (diagnóstico)
        run: az account show

      - name: ⚙️ Configurar comando de inicio (FastAPI con gunicorn)
        run: |
          az webapp config set --name gestionconsorcioexpress2 \
            --resource-group db_gestionexpress \
            --startup-file "gunicorn main:app --workers 4 --bind=0.0.0.0 --timeout 600"

      - name: 🔁 Reiniciar Web App antes del despliegue
        run: |
          az webapp restart --name gestionconsorcioexpress2 --resource-group db_gestionexpress

      - name: 🚀 Desplegar usando Run From Package
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gestionconsorcioexpress2"
          slot-name: "Production"
          package: release.zip
          deployment-method: "run-from-package"

      - name: 🧾 Logs de Oryx si falla el despliegue
        if: failure()
        run: |
          echo "❗ Despliegue fallido. Leyendo logs Oryx desde Kudu:"
          curl -s "https://gestionconsorcioexpress2.scm.azurewebsites.net/api/logs/oryx-build.log" || echo "No se pudo acceder a los logs"
