name: Build | Deploy Gestión Express en Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: 🛠️ Construcción del paquete
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar versión de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 📥 Instalar dependencias (validación)
        run: |
          pip install -r requirements.txt

      - name: 📦 Comprimir archivos para despliegue
        run: |
          zip -r release.zip *.py requirements.txt controller model view static lib -x "**/__pycache__/*" "**/*.pyc" "**/.DS_Store"

      - name: ☁️ Subir artefacto para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    name: 🚀 Despliegue en Azure App Service
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 📥 Descargar artefacto del trabajo de construcción
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 📂 Descomprimir paquete
        run: unzip release.zip

      - name: 🔐 Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2E151F66C35D4BA28D510A06161DA86F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FBEAC51370D5452AB2913F65AD0E4BEE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5A9C001E330B4F059F142C553755F6AF }}

      - name: 👤 Ver cuenta autenticada (diagnóstico)
        run: az account show

      - name: 🚀 Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gestionconsorcioexpress2"
          slot-name: "Production"
          package: .
