name: Build | Deploy Gestión Express en Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar versión de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: 📥 Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🔐 Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: 🚀 Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "gestionconsorcioexpress2"
          slot-name: "Production"
          package: .
