name: Compilar y desplegar app FastAPI en Azure Web App - gestionconsorcioexpress2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Clonar el repositorio
      - name: Clonar repositorio
        uses: actions/checkout@v4

      # Configurar la versión de Python
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # Crear entorno virtual (aunque no se usa luego en GitHub Actions, es opcional)
      - name: Crear entorno virtual
        run: |
          python -m venv venv
          source venv/bin/activate

      # Instalar dependencias desde requirements.txt
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # Preparar artefacto limpio para desplegar (excluye carpetas innecesarias)
      - name: Preparar paquete limpio para despliegue
        run: |
          mkdir package
          shopt -s extglob
          cp -r !(package) package
          rm -rf package/.github package/.git* package/venv package/.venv package/__pycache__
          zip -r release.zip package

      # Subir el ZIP como artefacto para la siguiente etapa
      - name: Subir artefacto para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      # Descargar el ZIP generado en el job anterior
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: python-app

      # Descomprimir el ZIP
      - name: Descomprimir artefacto
        run: unzip release.zip

      # Autenticarse en Azure
      - name: Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D5569479D42046A3AFF4F8337EF48497 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_14E2F77F7D044E1082233AFD02038510 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_987F9D9F7656498C8A3AD66D6FFDF60F }}

      # Desplegar en Azure App Service
      - name: Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "gestionconsorcioexpress2"
          slot-name: "Production"
