name: Build | Deploy Gestión Express en Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🔄 Clonar repositorio
        uses: actions/checkout@v4

      - name: 🐍 Configurar versión de Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: 📦 Crear y activar entorno virtual
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: 📥 Instalar dependencias
        run: pip install -r requirements.txt

      - name: 📦 Preparar paquete limpio para despliegue
        run: |
          shopt -s extglob
          zip -r release.zip . -x "venv/*" ".venv/*" "__pycache__/*" ".git/*" ".github/*" "release.zip"

      - name: ☁️ Subir artefacto para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 📥 Descargar artefacto del trabajo de compilación
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: 📂 Descomprimir artefacto para despliegue
        run: unzip release.zip

      - name: 🔐 Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D5569479D42046A3AFF4F8337EF48497 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_14E2F77F7D044E1082233AFD02038510 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_987F9D9F7656498C8A3AD66D6FFDF60F }}

      - name: 🚀 Desplegar en Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "gestionconsorcioexpress2"
          slot-name: "Production"
