name: Build and deploy Python app to Azure Web App - gestionconsorcioexpress2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # ✅ Empaquetar solo archivos limpios (sin .github, .venv, __pycache__, etc.)
      - name: Prepare clean package for deployment
        run: |
          mkdir package
          cp -r * package
          rm -rf package/.github package/.git* package/venv package/__pycache__ package/.venv
          zip -r release.zip package

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D5569479D42046A3AFF4F8337EF48497 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_14E2F77F7D044E1082233AFD02038510 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_987F9D9F7656498C8A3AD66D6FFDF60F }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "gestionconsorcioexpress2"
          slot-name: "Production"
